### PR TITLE
Features/caching metadata

### LINKED ISSUE #37: Caching Mechanism For Token Metadata
**Context:**
I can imagine there being a wall or gallery view of all the token's that have been issued, similar to when viewing: https://opensea.io/collection/devs-for-revolution that we might want to show later on a different page or use to show other data.

**Problem:**
Querying all this data each time is expensive when querying each token directly.

**Solution:**
Considering that all tokens are static (excluding ownership), their data won't change.
Create an script that would ping every individual token and generate a local json file to be used by the site.

### PR DESCRIPTION
**Pull request by codingwithmanny**
**Context:**
Fixes #37 

**Proposal:**
Script that pulls in data from mainnet for a local json file that can be used instead of pinging mainnet constantly.

Sample `data/data.json` can also be seen (currently only contains 10 because the process can take a while) 

Proposed JSON structure:

```json
{
  "contract": "0x25ed58c027921e14d86380ea2646e3a1b5c55a8b",
  "name": "Devs for Revolution",
  "owner": "0x91D7a9e7C09477392290FE16c1b243E4A36d279a",
  "symbol": "DEVS",
  "totalSupply": 2831,
  "tokens": [
    {
      "id": 1,
      "clothing": "White Tanktop",
      "industry": "Government",
      "language": "Scala",
      "location": "Kisumu",
      "mind": "Divergent",
      "os": "macOS",
      "textEditor": "Brackets",
      "vibe": "JonGold",
      "owner": "0x1A16c87927570239FECD343ad2654fD81682725e",
      "tokenURI": "data:application/json;base64,eyJuYW1lIjogIkRldiAjMSIsICJkZXNjcmlwdGlvbiI6ICJEZXZlbG9wZXJzIGFyb3VuZCB0aGUgd29ybGQgYXJlIHRpcmVkIG9mIHdvcmtpbmcgYW5kIGNvbnRyaWJ1dGluZyB0aGVpciB0aW1lIGFuZCBlZmZvcnQgdG8gZW5yaWNoIHRoZSB0b3AgMSUuIEpvaW4gdGhlIG1vdmVtZW50IHRoYXQgaXMgY29tbXVuaXR5IG93bmVkLCBidWlsZGluZyB0aGUgZnV0dXJlIGZyb20gdGhlIGJvdHRvbSB1cC4iLCAiaW1hZ2UiOiAiZGF0YTppbWFnZS9zdmcreG1sO2Jhc2U2NCxQSE4yWnlCNGJXeHVjejBpYUhSMGNEb3ZMM2QzZHk1M015NXZjbWN2TWpBd01DOXpkbWNpSUhCeVpYTmxjblpsUVhOd1pXTjBVbUYwYVc4OUluaE5hVzVaVFdsdUlHMWxaWFFpSUhacFpYZENiM2c5SWpBZ01DQXpOVEFnTXpVd0lqNDhjM1I1YkdVK0xtSmhjMlVnZXlCbWFXeHNPaUJpYkdGamF6c2dabTl1ZEMxbVlXMXBiSGs2SUhObGNtbG1PeUJtYjI1MExYTnBlbVU2SURFMGNIZzdJSDA4TDNOMGVXeGxQanh5WldOMElIZHBaSFJvUFNJeE1EQWxJaUJvWldsbmFIUTlJakV3TUNVaUlHWnBiR3c5SW5kb2FYUmxJaUF2UGp4MFpYaDBJSGc5SWpFd0lpQjVQU0l5TUNJZ1kyeGhjM005SW1KaGMyVWlQbTFoWTA5VFBDOTBaWGgwUGp4MFpYaDBJSGc5SWpFd0lpQjVQU0kwTUNJZ1kyeGhjM005SW1KaGMyVWlQa0p5WVdOclpYUnpQQzkwWlhoMFBqeDBaWGgwSUhnOUlqRXdJaUI1UFNJMk1DSWdZMnhoYzNNOUltSmhjMlVpUGxkb2FYUmxJRlJoYm10MGIzQThMM1JsZUhRK1BIUmxlSFFnZUQwaU1UQWlJSGs5SWpnd0lpQmpiR0Z6Y3owaVltRnpaU0krVTJOaGJHRThMM1JsZUhRK1BIUmxlSFFnZUQwaU1UQWlJSGs5SWpFd01DSWdZMnhoYzNNOUltSmhjMlVpUGtkdmRtVnlibTFsYm5ROEwzUmxlSFErUEhSbGVIUWdlRDBpTVRBaUlIazlJakV5TUNJZ1kyeGhjM005SW1KaGMyVWlQa3RwYzNWdGRUd3ZkR1Y0ZEQ0OGRHVjRkQ0I0UFNJeE1DSWdlVDBpTVRRd0lpQmpiR0Z6Y3owaVltRnpaU0krUkdsMlpYSm5aVzUwUEM5MFpYaDBQangwWlhoMElIZzlJakV3SWlCNVBTSXhOakFpSUdOc1lYTnpQU0ppWVhObElqNUtiMjVIYjJ4a1BDOTBaWGgwUGp3dmMzWm5QZz09In0=",
      "tokenURIParsed": {
        "name": "Dev #1",
        "description": "Developers around the world are tired of working and contributing their time and effort to enrich the top 1%. Join the movement that is community owned, building the future from the bottom up.",
        "image": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHByZXNlcnZlQXNwZWN0UmF0aW89InhNaW5ZTWluIG1lZXQiIHZpZXdCb3g9IjAgMCAzNTAgMzUwIj48c3R5bGU+LmJhc2UgeyBmaWxsOiBibGFjazsgZm9udC1mYW1pbHk6IHNlcmlmOyBmb250LXNpemU6IDE0cHg7IH08L3N0eWxlPjxyZWN0IHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9IndoaXRlIiAvPjx0ZXh0IHg9IjEwIiB5PSIyMCIgY2xhc3M9ImJhc2UiPm1hY09TPC90ZXh0Pjx0ZXh0IHg9IjEwIiB5PSI0MCIgY2xhc3M9ImJhc2UiPkJyYWNrZXRzPC90ZXh0Pjx0ZXh0IHg9IjEwIiB5PSI2MCIgY2xhc3M9ImJhc2UiPldoaXRlIFRhbmt0b3A8L3RleHQ+PHRleHQgeD0iMTAiIHk9IjgwIiBjbGFzcz0iYmFzZSI+U2NhbGE8L3RleHQ+PHRleHQgeD0iMTAiIHk9IjEwMCIgY2xhc3M9ImJhc2UiPkdvdmVybm1lbnQ8L3RleHQ+PHRleHQgeD0iMTAiIHk9IjEyMCIgY2xhc3M9ImJhc2UiPktpc3VtdTwvdGV4dD48dGV4dCB4PSIxMCIgeT0iMTQwIiBjbGFzcz0iYmFzZSI+RGl2ZXJnZW50PC90ZXh0Pjx0ZXh0IHg9IjEwIiB5PSIxNjAiIGNsYXNzPSJiYXNlIj5Kb25Hb2xkPC90ZXh0Pjwvc3ZnPg=="
      }
    },
  ]
}
```

**Notes:**
Please see `README.md` for the section of `### Generatiing Static Data` for details and warnings.

**Possible Recommendation:**
We spin off this script into a separate repository and figure out a way to use it as a `npx` command when needed.

### CODE REVIEW

**Comment by will-t-harris** [comment]
Since we're already deploying the site to Vercel, perhaps it makes sense to deploy this as a serverless function?

**Comment by codingwithmanny** [comment]
@will-t-harris I would love that but if you ever run it, it'll take 22h (yes hours) to finish 😂

**Comment by with-heart** [comment]
> We spin off this script into a separate repository and figure out a way to use it as a `npx` command when needed.

I'm thinking this might be the right direction to head? Seems like the resulting `.json` artifact is useful to the project, but is the script itself? Not sure, would love to be convinced either way!

**Comment by codingwithmanny** [comment]
@with-heart agree. The script itself isn't entirely part of the website but the data is. Would it be possible to create another repo for this? I'm also thinking to refactor a bit so that you can specify which tokenId you want pulled so it updates that in the JSON file.

**Comment by codingwithmanny** [comment]
Figured out a way to use the script with npx if we decide to move it to another repository.

(In new repository)

**File:** `package.json`

```json
{
  "bin": "./index.js",
 }
```

In this repository:

**File:** `package.json`

```js
  "scripts": {
     "data": "npx https://github.com/org/repo"
   }
```

**Comment by codingwithmanny** [comment]
@with-heart You think we should create a separate repo or I could move this to my person repo for now and then figure it out from there in the meantime.

**Comment by codingwithmanny** [comment]
Going to close this and make it a separate person repo for now until we decide to make one for developer dao.

**Comment by with-heart** [comment]
Whoops, didn't mean to ignore you! Yeah I think that's a good direction for the time being. Not sure how to best integrate that with the site at this point

**Pull request closed without merging**
