### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ACollectionOfAtoms**
Just a lil' typo fixypoo

### CODE REVIEW

**Review by codingwithmanny — APPROVED** [review]
Looks good _TO_ me

**Review by Canopix — APPROVED** [review]
I think this work is impressive !

**Comment by with-heart** [comment]
I'm literally blown away 😁 

Welcome aboard!

**Comment by with-heart** [comment]
@allcontributors please add @ACollectionOfAtoms for docs

**Pull request merged**
