### PR TITLE
Translation Nesting [Issue #91]

### PR DESCRIPTION
**Pull request by TrevorFrench**
### What does it do?
Adds nesting for translation files.

### Any helpful background information?
Realized the "zh" files are a little above my head.

### Any new dependencies? Why were they added?
N/A

### Relevant screenshots/gifs
N/A

### Does it close any issues?
N/A

Related to #91

### CODE REVIEW

**Comment by TrevorFrench** [comment]
Sorry, I thought I was up to date with the base branch :disappointed_relieved:

**Comment by narbs91** [comment]
The changes look good to me @TrevorFrench but like you mentioned some of the files you weren't able to decipher, perhaps you can ask in the discord channel if anyone could assist with the remaining files?

**Comment by TrevorFrench** [comment]
@narbs91 good idea. I'll get on it!

**Review by with-heart — APPROVED** [review]
This looks good! 

@TrevorFrench could you open a ["missing translation" issue](https://github.com/Developer-DAO/developer-dao/issues/new?assignees=&labels=translation&template=missing-translations.yml&title=Missing+Translation%28s%29) and fill that out so we can track the translations that are missing? That way we can just move forward with what you have and translators can resolve missing translations later.

**Comment by with-heart** [comment]
@allcontributors please add @TrevorFrench for translation and code

**Pull request merged**
