### PR TITLE
Tech/next i18next

### PR DESCRIPTION
**Pull request by gjsyme**
Address #49 and step forward to put the RU, ZHSC, and ZHTC into the common.json structure required by the new i18n format. Remove the old dependencies and configurations for other i18n systems, and update Contributing page to no longer refer to them and correctly refer to next-i18next. Change PropTypes for children to PropTypes.object to remove the warning (PropTypes.children was undefined). Add myself to contributors for code.

### CODE REVIEW

**Comment by with-heart** [comment]
Oof! We need to document this in `CONTRIBUTING.md` but we're using `yarn` for this project. You'll want to remove `package-lock.json` :)

**Review by with-heart — CHANGES_REQUESTED** [review]
Mostly looks good to me! 

I merged the PRs for the Chinese and Russian translations so those users would get the credit for commits, so we'll need to rebase the changes and then remove those files from `src/locales`. 

Happy to help with the rebase if you need it!

**Comment by with-heart** [comment]
Hey buddy! I saw your messages on Discord about rebasing and noticed that the commits are in quite a bit of disarray. No big deal! We can fix anything in git history thanks to `rebase` :)

I'm not entirely sure how things got into this exact state, but I'll walk you through what I do to fix it!

1. Update my local `main` branch using `git pull`. This makes the latest commit of `main` (`HEAD`) match `HEAD` of `origin/main`. Now we have the latest changes!

2. Switch to your branch using `git pr checkout 57`

3. Now that we're on your branch, we're going to `rebase` the changes onto `main`. What this means is that `git` will start from `HEAD` of `main` branch and then "replay" your commits on top of it one-by-one. Once `rebase` is finished, your branch will match `main` plus the unique changes from your branch.

	So let's run `git rebase main`! `rebase` makes it to the third commit on your branch before it runs into a conflict:

	image
	
4. Let's run `git status` to see which files have conflicts. I have a custom `status` command so it'll look different than yours, but the meaning is the same.

	image

5. Let's resolve the conflict in `.all-contributorsrc`!
	
	image
	
	The section between `<<<` and `===` is the code in `HEAD` (the latest commit, so the 2nd commit of your branch) and the section between `===` and `>>>` is the code in the next commit that's causing the conflict. Looks like in this case, the other two contributors were in the file but your commit only had you.

	We can resolve this conflict by just removing the `<<<`, `===`, and `>>>` lines ("conflict markers", since we want to end up with all three of you in the file:

	image

6. Now let's resolve the conflict in `next-i18next.config.js`!

	image

	I'm not entirely sure why this is a merge conflict but, since we want to end up with all of the languages in this array, we'll go ahead and remove the conflict markers and the incomplete array:

	image

7. Cool! Now that we've resolved the conflicts, let's go ahead and continue on with `rebase`. First we'll add the changes using `git add .` and then continue using `git rebase --continue`.

8. Awesome! `rebase` is finished. Let's look at the commits we're left with using `git log`. I'm using a custom `log` command that's heavily abbreviated, so it'll look different than yours:

	image

	History starts from `main` and only includes the three unique commits from your branch! Since all of the other commits that got mixed into your branch were duplicates that already existed in `main`, `rebase` has gone ahead and removed them as they're not needed.

	It shows me as the author, but in reality, we're now co-authors of those commits since I'm the one that most recently modified their history. We'll both receive credit for those commits and GitHub will show my face next to yours in the commit history.

9. To finish it off, I'll go ahead and force-push to your branch using `git push --force` so the changes are reflected here on GitHub.

**Comment by with-heart** [comment]
GitHub now correctly shows only the commits from your branch:

image

Yay!

One other thing I noticed is that since you installed dependencies using `npm`, `yarn.lock` wasn't updated with the latest installation. So I ran `yarn` to install them and committed the changes to `yarn.lock`.

**Comment by with-heart** [comment]
Made one final change (I think!). Added a little extra context to the `yarn` note in `CONTRIBUTING.md`.

**Review by with-heart — APPROVED** [review]
I think this is now good to go! Could use some testing from the other languages to make sure it's working as expected, but I would love to get this merged soon!

**Comment by with-heart** [comment]
Also wanted to share two concepts with you that I think will take you a long way in contributing to open source!

The first is "atomic commits": https://dev.to/paulinevos/atomic-commits-will-help-you-git-legit-35i7

The second is how to write a good commit message: https://chris.beams.io/posts/git-commit/

The two are somewhat related as atomic commits result in commits that are easy to describe.

**Review by codingwithmanny — APPROVED** [review]
LGTM. I looked over this the other night with @gjsyme.

**Pull request merged**
