### PR TITLE
WIP: vitejs

### PR DESCRIPTION
**Pull request by codingwithmanny**
**Context:**
See #22 - ViteJS vs CRA

**What's Working:**
1 - Development environment shows up fast - `yarn dev`
2 - Build process works - `yarn build`
3 - Serve process work - `yarn serve`

**Not Working:**
4 - Jest tests are currently working (may need some help with this)

**Tests Performed:**
5 - `yarn dev` ✅  - http://localhost:3000 works
6 - `yarn build` ✅ - created `dist` folder and then quickly served with `npx http-server ./dist -p 8000;`
7 - `yarn serve` ✅ - http://localhost:5000 works

**Haven't Tests:**
8 - If multilingual is working correctly when changing system language

### CODE REVIEW

**Comment by with-heart** [comment]
Gonna convert this to a draft PR, just to make it clear it's WIP and shouldn't be merged before we discuss more :)

**Comment by with-heart** [comment]
We'll have to change the Vercel configuration around if we go that route. Shouldn't be a big deal, but just throwing that out there as the reason why the deploy is failing atm.

**Comment by codingwithmanny** [comment]
> Gonna convert this to a draft PR, just to make it clear it's WIP and shouldn't be merged before we discuss more :)

@with-heart sounds good to me.

> We'll have to change the Vercel configuration around if we go that route. Shouldn't be a big deal, but just throwing that out there as the reason why the deploy is failing atm.

@with-heart yeah I figured it's because it's a different dist / build folder.

**Comment by codingwithmanny** [comment]
Based on the conversation and the findings in https://github.com/Developer-DAO/developer-dao/issues/22#issuecomment-917644600, I'm going to close this draft PR.

**Pull request closed without merging**
