### PR TITLE
Add Vercel sponsorship info

### PR DESCRIPTION
**Pull request by thomasmetta**
**Why**
Thanks to @dbredvick for checking with the DevRel team to help us get sponsorship with Vercel

We need to add a vercel banner in the site and read to meet the Sponsorship Criteria https://vercel.com/support/articles/can-vercel-sponsor-my-open-source-project

**What changed**

- Add vercel banner in the footer 
- Add vercel banner in the README.md

### CODE REVIEW

**Comment by leerob** [comment]
Happy to sponsor y’all 🙏🏼🤩

**Review by with-heart — APPROVED** [review]

**Comment by with-heart** [comment]
Thanks so much @leerob and all yall at Vercel!

**Comment by codingwithmanny** [comment]
@thomasmetta you mind if we remove the `Hosting is` in the translations all together. If you did the translations in `es` and `fr` it doesn't necessarily make sense.

Ex French (it technically works sorta but might not work in Spanish):
```
l'hébergement est "Powered by Vercel"
```

**Comment by with-heart** [comment]
@codingwithmanny Should be fine! Sponsorship just requires a banner in the footer.

**Comment by thomasmetta** [comment]
@codingwithmanny I didn't really want to add it but it might be confusing for new users since they might think the smart contract is powered by Vercel

**Comment by codingwithmanny** [comment]
@thomasmetta thoughts on this proposal https://github.com/Developer-DAO/developer-dao/pull/41#discussion_r708058706 ?

**Pull request merged**
