### PR TITLE
feat: sync URL state with current NFT ID

### PR DESCRIPTION
**Pull request by Dhaiwat10**
Context — #43 

The query param — NFT ID integration was broken for some reason (try visiting https://www.developerdao.com/?id=5350). The problem was that `router.query.id` was coming up as `undefined` on the first render & hence the variable `id` was defaulting to `1`.

~~To fix this, I switched from static site generation to SSR (you cannot get query params from the server in SSG because the page is...well, static. It's only rendered once, at build time).~~ Everything now works.

### CODE REVIEW

**Comment by Dhaiwat10** [comment]
Would be a good idea to get this reviewed by several people since switching from completely static to SSR is kind of an important thing.

**Comment by Dhaiwat10** [comment]
Also, not sure why the Vercel preview deployment is returning a 404 error. Could someone with access to the Vercel account look into this? I don't think Vercel has deployed this PR, but then again Github is showing me that all 2 checks have passed.

image

**Comment by codingwithmanny** [comment]
@Dhaiwat10 can you check the other languages as well to see that it's working.

Ex: 
- `/fr/?id=1` should work
- `/es/?id=7899` should fail

**Comment by Dhaiwat10** [comment]
@codingwithmanny both of them are not working. Getting the same error in both the cases. (why though?)

image

**Comment by codingwithmanny** [comment]
@Dhaiwat10 looks like a case of Developer Sherlock Holmes and SO 😂 
but for real @gjsyme might be able to help, he helped build these sections.

**Comment by Dhaiwat10** [comment]
image

jokes aside, we NEED tests

**Comment by Dhaiwat10** [comment]
Btw https://www.developerdao.com/fr?id=5350 and https://www.developerdao.com/es?id=5350 both don't work either. :/

**Comment by Dhaiwat10** [comment]
^ This makes me think that the bug was probably not introduced in this PR. Stuff was already broken (?)

**Comment by Dhaiwat10** [comment]
Massive thanks to @CristinaSolana for suggesting this vanilla JS fix. No need to switch to SSR anymore. I think we can merge this now

**Comment by with-heart** [comment]
Looks like the runtime error is caused by Google Translate 😬 https://github.com/facebook/react/issues/11538

**Review by with-heart — APPROVED** [review]
Nice work @Dhaiwat10!

**Comment by Dhaiwat10** [comment]
> Looks like the runtime error is caused by Google Translate 😬 https://github.com/facebook/react/issues/11538

you're right. it's not crashing on firefox.

bloody hell.

**Comment by with-heart** [comment]
> bloody hell.

Indeed! Pretty dumb lol but oh well

**Pull request merged**
