### PR TITLE
Added unclaimed if no owner + translations

### PR DESCRIPTION
**Pull request by codingwithmanny**
**Context:**
Noticed that when you entered a dev# that was not claimed, the owner field came out blank.
Decided to add the word `unclaimed` with the English and Spanish translations.

**Before:**
Screen Shot 2021-09-10 at 4 46 41 PM

**Proposal:**
Screen Shot 2021-09-10 at 4 47 41 PM

### CODE REVIEW

**Review by xdrdak — APPROVED** [review]
lgtm

**Comment by codingwithmanny** [comment]
Conflicts resolved.

**Review by with-heart — COMMENTED** [review]
Wanna add the `fr` translation to this since that's been merged?

**Review by with-heart — APPROVED** [review]

**Comment by codingwithmanny** [comment]
@with-heart done ✅

**Pull request merged**
